name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - run: npm ci

      - run: npm run build

      - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        id: pinata
        with:
          pin-name: 'My personal site'
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
          verbose: true
          remove-old: false
