name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - run: npm ci

      - run: npm run build

      - uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          pinName: "Staking-Test_Deployment"
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          verbose: true
      - name: Output IPFS Hash
        run: echo "The IPFS hash is ${{ steps.upload.outputs.hash }}"
