name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - run: npm ci

      - run: npm run build

      - name: Pin to IPFS
        uses: aquiladev/ipfs-action@master
        id: pinata
        with:
          path: ./build
          pinName: "staking ui"
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          verbose: true

      - name: Output IPFS Hash
        run: echo "The IPFS hash is ${{ steps.pinata.outputs.hash }}"

      - name: Convert CIDv0 to CIDv1
        id: convert-cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.pinata.outputs.hash }}

      - name: Use CIDv1
        run: echo ${{ steps.convert-cidv0.outputs.cidv1 }}
